
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: CI CoE Pilot
subtitle: "NSF Pilot Study Cyberinfrastructure Center of Excellence"

# Build settings
markdown: kramdown
permalink: pretty
