- categroy: Workshop
  end_date: September 16, 2021
  source: XSEDE
  start_date: September 16, 2021
  time: 04:00
  title: 'XSEDE Webinar: Accessing and Running Jobs on Expanse'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2530/session/4224/register"
- categroy: Workshop
  end_date: September 16, 2021
  source: XSEDE
  start_date: September 16, 2021
  time: 04:00
  title: Writing a Successful XSEDE Allocation Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/4258/register"
- categroy: Workshop
  end_date: September 24, 2021
  source: TACC
  start_date: September 23, 2021
  time: 04:00
  title: TACCSTER 20
  website: "https://learn.tacc.utexas.edu/course/view.php?id=108"
- categroy: Workshop
  end_date: October 06, 2021
  source: XSEDE
  start_date: October 05, 2021
  time: 04:00
  title: 'XSEDE HPC Workshop: Big Data and Machine Learning - October 5-6, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2563/session/4259/register"
- categroy: Workshop
  end_date: October 13, 2021
  source: XSEDE
  start_date: October 06, 2021
  time: 04:00
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Agent-based Modeling'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2366/session/4257/register"
- categroy: Workshop
  end_date: October 13, 2021
  source: XSEDE
  start_date: October 06, 2021
  time: 04:00
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    3) Agent-based Modeling'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2366/session/4257/register"
- categroy: Workshop
  end_date: October 21, 2021
  source: XSEDE
  start_date: October 21, 2021
  time: 04:00
  title: 'XSEDE Webinar: Data Management & File Systems on Expanse'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2531/session/4225/register"
- categroy: Workshop
  end_date: November 10, 2021
  source: CyVerse
  start_date: November 07, 2021
  time: 04:00
  title: A Creative Economy for Sustainable Development
  website: "https://cyverse.org/acsmeeting2021"