- categroy: Workshop
  date: March 09, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Arizona State University)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3644/register"
- categroy: Workshop
  date: March 18, 2020
  title: Writing a Successful XSEDE Allocation Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/3632/register"
- categroy: Workshop
  date: March 19, 2020
  title: 'XSEDE Webinar: Using the Seedme Data Management System on Comet'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2035/session/3630/register"
- categroy: Workshop
  date: March 19, 2020
  title: 'XSEDE Webinar: Using the SeedMeLab Data Management System on Comet'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2035/session/3630/register"
- categroy: Workshop
  date: March 20, 2020
  title: XSEDE New User Training March 20, 2020
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2040/session/3635/register"
- categroy: Workshop
  date: March 21, 2020
  title: CSULA Student Training Series 2020- XSEDE Python 1 in Linux/Unix (Cal State
    LA)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2014/session/3525/register"
- categroy: Workshop
  date: March 28, 2020
  title: CSULA Student Training Series 2020- XSEDE Python 2 in Linux/Unix (Cal State
    LA)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2015/session/3526/register"
- categroy: Workshop
  date: April 02, 2020
  title: Introduction to Research Computing Using the Illinois Campus Cluster (Illini
    Hall, University of Illinois at Urbana-Champaign)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2039/session/3634/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Pittsburgh Supercomputing
    Center)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3636/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Georgia Institute of Technology)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3637/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Stanford University)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3639/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (The University of Utah)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3648/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (New York University)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3649/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Pennsylvania State University)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3650/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (University of California,
    Los Angeles)
  website: "Registration opens"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (University of Houston)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3652/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (University of South Carolina)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3653/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (University of Delaware)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3654/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Ohio Supercomputer Center)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3655/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Pomona College)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3656/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (University of Tennessee Knoxville
    - NICS)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3657/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (National Center for Supercomputing
    Applications)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3658/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Tufts University)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3641/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Purdue University)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3642/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (University of Cincinnati)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3643/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (University of Houston - Clear
    Lake)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3645/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (East Carolina University)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3646/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Yale Center for Research Computing)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3647/register"
- categroy: Workshop
  date: April 07, 2020 - April 08, 2020
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (George Mason University)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2041/session/3640/register"
- categroy: Workshop
  date: June 01, 2020 - June 05, 2020
  title: Computational Chemistry for Chemistry Educators Workshop (Mount Saint Mary
    College)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2038/session/3633/register"