- categroy: Workshop
  end_date: April 06, 2021
  source: XSEDE
  start_date: April 06, 2021
  time: ''
  title: XSEDE Code Performance and Scaling Training
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2332/session/3993/register"
- categroy: Workshop
  end_date: April 07, 2021
  source: XSEDE
  start_date: April 06, 2021
  time: ''
  title: 'XSEDE HPC Workshop: Big Data and Machine Learning - April 6-7, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2313/session/3973/register"
- categroy: Workshop
  end_date: April 15, 2021
  source: XSEDE
  start_date: April 15, 2021
  time: ''
  title: XSEDE Webinar - Composable Systems in Expanse, Thursday, April 15, 2021,
    11am-12pm PT
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2314/session/3974/register"
- categroy: Workshop
  end_date: April 15, 2021
  source: XSEDE
  start_date: April 15, 2021
  time: ''
  title: New User Training- University of Central Florida
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2303/session/3963/register"
- categroy: Workshop
  end_date: April 21, 2021
  source: XSEDE
  start_date: April 21, 2021
  time: ''
  title: 'XSEDE Webinar: AMD EPYC Advanced User Training on Expanse, Wednesday, April
    21, 2021, 9am-1:30pm PT'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2311/session/3971/register"
- categroy: Workshop
  end_date: April 22, 2021
  source: XSEDE
  start_date: April 22, 2021
  time: ''
  title: Rich data sharing for HPC Users
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2315/session/3976/register"
- categroy: Workshop
  end_date: April 22, 2021
  source: XSEDE
  start_date: April 22, 2021
  time: ''
  title: Light data sharing for HPC Users
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2315/session/3976/register"