- categroy: Workshop
  end_date: October 22, 2021
  source: CyVerse
  start_date: October 22, 2021
  time: 04:00
  title: 'Webinar: All About Apps in CyVerse'
  website: "https://cyverse.org/apps-webinar"
- categroy: Workshop
  end_date: November 03, 2021
  source: XSEDE
  start_date: November 03, 2021
  time: 04:00
  title: 'XSEDE HPC Workshop: OpenMP - November 3, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2567/session/4265/register"
- categroy: Workshop
  end_date: November 10, 2021
  source: CyVerse
  start_date: November 07, 2021
  time: 04:00
  title: A Creative Economy for Sustainable Development
  website: "https://cyverse.org/acsmeeting2021"