- categroy: Workshop
  end_date: June 21, 2022
  source: XSEDE
  start_date: June 13, 2022
  time: 04:00
  title: Computational Chemistry for Chemistry Educators Workshop
  website: "Registration closed"
- categroy: Workshop
  end_date: June 14, 2022
  source: XSEDE
  start_date: June 14, 2022
  time: 04:00
  title: Writing a Successful XSEDE Research Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/4522/register"
- categroy: Workshop
  end_date: June 16, 2022
  source: XSEDE
  start_date: June 16, 2022
  time: 04:00
  title: 'XSEDE Webinar | Run your Jupyter Notebooks anywhere: Scaling up your Projects
    from Laptop to Expanse'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2992/session/4752/register"
- categroy: Workshop
  end_date: June 24, 2022
  source: XSEDE
  start_date: June 19, 2022
  time: 04:00
  title: IHPCSS 2022 Hands-on Training (Novotel Athenes)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/3025/session/4785/register"
- categroy: Workshop
  end_date: June 23, 2022
  source: XSEDE
  start_date: June 23, 2022
  time: 04:00
  title: Advanced Computing for Social Change Curriculum Workshop
  website: "Registration opens"
- categroy: Workshop
  end_date: June 30, 2022
  source: InCommon
  start_date: June 28, 2022
  time: 04:00
  title: COmanage Class
  website: "'https://service5.internet2.edu/reg/events/coman22-06/registrations '"
- categroy: Workshop
  end_date: July 08, 2022
  source: XSEDE
  start_date: July 08, 2022
  time: 04:00
  title: Writing a Successful XSEDE Research Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/4719/register"