- categroy: Workshop
  end_date: August 11, 2021
  source: XSEDE
  start_date: August 10, 2021
  time: 04:00
  title: 'XSEDE HPC Workshop: Big Data and Machine Learning - August 10-11, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2433/session/4094/register"
- categroy: Workshop
  end_date: August 27, 2021
  source: CyVerse
  start_date: August 27, 2021
  time: 04:00
  title: 'Webinar: CyVerse 2021 for Research, Teaching and Open Science'
  website: "https://cyverse.org/node/243"
- categroy: Workshop
  end_date: August 27, 2021
  source: CyVerse
  start_date: August 27, 2021
  time: 04:00
  title: "Webinar: Get It Done with CyVerse: Real Life Stories of\_Research, Teaching\
    \ and Open Science"
  website: "https://cyverse.org/cyverse2021"
- categroy: Workshop
  end_date: September 24, 2021
  source: TACC
  start_date: September 23, 2021
  time: 04:00
  title: TACCSTER 20
  website: "https://learn.tacc.utexas.edu/course/view.php?id=108"
- categroy: Workshop
  end_date: November 10, 2021
  source: CyVerse
  start_date: November 07, 2021
  time: 04:00
  title: A Creative Economy for Sustainable Development
  website: "https://cyverse.org/acsmeeting2021"