- categroy: Workshop
  end_date: January 06, 2021
  source: XSEDE
  start_date: January 06, 2021
  time: ''
  title: XSEDE Code Performance and Scaling Training
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2240/session/3903/register"
- categroy: Workshop
  end_date: January 07, 2021
  source: XSEDE
  start_date: January 07, 2021
  time: ''
  title: Writing a Successful XSEDE Allocation Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/3902/register"
- categroy: Workshop
  end_date: January 12, 2021
  source: XSEDE
  start_date: January 12, 2021
  time: ''
  title: 'XSEDE HPC Workshop: OpenMP - January 12, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2237/session/3899/register"
- categroy: Workshop
  end_date: January 21, 2021
  source: XSEDE
  start_date: January 21, 2021
  time: ''
  title: 'XSEDE Webinar: An Introduction to Singularity: Containers for Scientific
    and High-Performance Computing'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2238/session/3900/register"
- categroy: Workshop
  end_date: February 02, 2021
  source: TACC
  start_date: February 02, 2021
  time: ''
  title: Introduction to Machine Learning at TACC
  website: "https://learn.tacc.utexas.edu/course/view.php?id=99"
- categroy: Workshop
  end_date: February 09, 2021
  source: TACC
  start_date: February 09, 2021
  time: ''
  title: Introduction to Deep Learning at TACC
  website: "https://learn.tacc.utexas.edu/course/view.php?id=100"
- categroy: Workshop
  end_date: February 10, 2021
  source: TACC
  start_date: February 10, 2021
  time: ''
  title: Introduction to Linux
  website: "https://learn.tacc.utexas.edu/course/view.php?id=101"
- categroy: Workshop
  end_date: February 18, 2021
  source: XSEDE
  start_date: February 18, 2021
  time: ''
  title: 'XSEDE Webinar: Performance Tuning and Single Processor Optimization, Thursday,
    Feb. 18, 2021, 11am-12pm PT'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2239/session/3901/register"
- categroy: Workshop
  end_date: February 18, 2021
  source: TACC
  start_date: February 18, 2021
  time: ''
  title: C++ for C Programmers
  website: "https://learn.tacc.utexas.edu/course/view.php?id=102"
- categroy: Workshop
  end_date: February 25, 2021
  source: TACC
  start_date: February 25, 2021
  time: ''
  title: MPL Object-Oriented Interface to MPI
  website: "https://learn.tacc.utexas.edu/course/view.php?id=103"