- categroy: Workshop
  end_date: August 31, 2022
  source: XSEDE
  start_date: August 30, 2022
  time: 04:00
  title: 'XSEDE HPC Workshop: Big Data and Machine Learning - August 30-21, 2022'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/3124/session/4917/register"