- categroy: Workshop
  end_date: January 11, 2022
  source: XSEDE
  start_date: January 11, 2022
  time: 05:00
  title: Writing a Successful XSEDE Research Proposal
  website: "Registration opens"
- categroy: Workshop
  end_date: January 20, 2022
  source: XSEDE
  start_date: January 20, 2022
  time: 05:00
  title: 'XSEDE Webinar: Parallel Computing Concepts'
  website: "Registration opens"
- categroy: Workshop
  end_date: February 17, 2022
  source: XSEDE
  start_date: February 17, 2022
  time: 05:00
  title: 'XSEDE Webinar: Accessing and Running Jobs on Expanse'
  website: "Registration opens"
- categroy: Workshop
  end_date: March 17, 2022
  source: XSEDE
  start_date: March 17, 2022
  time: 04:00
  title: "XSEDE Webinar: Singularity \u2013 Containers for Scientific and High-Performance\
    \ Computing"
  website: "Registration opens"