- categroy: Workshop
  end_date: May 05, 2021
  source: XSEDE
  start_date: May 04, 2021
  time: ''
  title: 'XSEDE HPC Workshop: MPI - May 4-5, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2336/session/3999/register"
- categroy: Workshop
  end_date: May 05, 2021
  source: XSEDE
  start_date: May 05, 2021
  time: ''
  title: XSEDE New User Training
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/1771/session/4000/register"
- categroy: Workshop
  end_date: May 20, 2021
  source: XSEDE
  start_date: May 20, 2021
  time: ''
  title: 'XSEDE Webinar: GPU Computing and Programming on Expanse, Thursday, May 20,
    2021, 11am-12pm PT'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2337/session/4001/register"
- categroy: Workshop
  end_date: May 27, 2021
  source: XSEDE
  start_date: May 27, 2021
  time: ''
  title: 'Webinar: Introduction to Computational Thinking Across the Curriculum'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2334/session/3997/register"
- categroy: Workshop
  end_date: June 15, 2021
  source: XSEDE
  start_date: June 07, 2021
  time: ''
  title: Computational Chemistry for Chemistry Educators Workshop
  website: "Registration opens"
- categroy: Workshop
  end_date: June 11, 2021
  source: XSEDE
  start_date: June 08, 2021
  time: ''
  title: 'HPC Workshop Series: Summer Boot Camp - June 8-11, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2338/session/4002/register"
- categroy: Workshop
  end_date: June 16, 2021
  source: XSEDE
  start_date: June 15, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Using
    Spreadsheets'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 16, 2021
  source: XSEDE
  start_date: June 15, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Modeling with Spreadsheets'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 18, 2021
  source: XSEDE
  start_date: June 17, 2021
  time: ''
  title: 'Workshop: Advanced Computing for Social Change Curriculum Development'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2335/session/3998/register"
- categroy: Workshop
  end_date: June 23, 2021
  source: XSEDE
  start_date: June 22, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Systems
    Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 23, 2021
  source: XSEDE
  start_date: June 22, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Using
    Systems Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 23, 2021
  source: XSEDE
  start_date: June 22, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Systems Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Using
    Agent Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Agent Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Agent-based Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Agent
    Modeling'
  website: "Registration opens"