- categroy: Workshop
  end_date: September 09, 2021
  source: CyVerse
  start_date: September 08, 2021
  time: 04:00
  title: 'AG2PI Workshop #7: Unix Skills and Git Skills'
  website: "https://cyverse.org/ag2pi-workshop-7"
- categroy: Workshop
  end_date: September 10, 2021
  source: CyVerse
  start_date: September 10, 2021
  time: 04:00
  title: 'Webinar: Discover the New Discovery Environment!'
  website: "https://cyverse.org/newDE"
- categroy: Workshop
  end_date: September 15, 2021
  source: XSEDE
  start_date: September 14, 2021
  time: 04:00
  title: 'XSEDE HPC Workshop: MPI - September 14-15, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2498/session/4192/register"
- categroy: Workshop
  end_date: September 16, 2021
  source: XSEDE
  start_date: September 16, 2021
  time: 04:00
  title: 'XSEDE Webinar: Accessing and Running Jobs on Expanse'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2530/session/4224/register"
- categroy: Workshop
  end_date: September 24, 2021
  source: TACC
  start_date: September 23, 2021
  time: 04:00
  title: TACCSTER 20
  website: "https://learn.tacc.utexas.edu/course/view.php?id=108"
- categroy: Workshop
  end_date: October 21, 2021
  source: XSEDE
  start_date: October 21, 2021
  time: 04:00
  title: 'XSEDE Webinar: Data Management & File Systems on Expanse'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2531/session/4225/register"
- categroy: Workshop
  end_date: November 10, 2021
  source: CyVerse
  start_date: November 07, 2021
  time: 04:00
  title: A Creative Economy for Sustainable Development
  website: "https://cyverse.org/acsmeeting2021"