- categroy: Workshop
  end_date: May 06, 2020
  source: XSEDE
  start_date: May 05, 2020
  time: ''
  title: XSEDE HPC Workshop MPI - May 5-6, 2020
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2053/session/3670/register"
- categroy: Workshop
  end_date: May 21, 2020
  source: LCI
  start_date: May 19, 2020
  time: ''
  title: LCI Advanced Workshop
  website: "http://linuxclustersinstitute.org/workshops/advanced20/register.php"
- categroy: Workshop
  end_date: May 21, 2020
  source: XSEDE
  start_date: May 21, 2020
  time: ''
  title: 'XSEDE Webinar: Running Jupyter Notebooks on Comet'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2042/session/3661/register"
- categroy: Workshop
  end_date: May 28, 2020
  source: XSEDE
  start_date: May 28, 2020
  time: ''
  title: 'XSEDE Webinar: Python and Performance'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2055/session/3672/register"
- categroy: Workshop
  end_date: June 10, 2020
  source: XSEDE
  start_date: June 01, 2020
  time: ''
  title: Computational Chemistry for Chemistry Educators Workshop
  website: "Registration closed"
- categroy: Workshop
  end_date: June 05, 2020
  source: XSEDE
  start_date: June 01, 2020
  time: ''
  title: Computational Chemistry for Chemistry Educators Workshop (Mount Saint Mary
    College)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2038/session/3633/register"
- categroy: Workshop
  end_date: June 05, 2020
  source: XSEDE
  start_date: June 02, 2020
  time: ''
  title: XSEDE HPC Workshop Summer Boot Camp - June 2-5, 2020
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2054/session/3671/register"