- categroy: Workshop
  end_date: December 04, 2020
  source: InCommon
  start_date: December 01, 2020
  time: ''
  title: Shibboleth Training
  website: "https://incommon.org/academy/shibboleth/"
- categroy: Workshop
  end_date: December 01, 2020
  source: XSEDE
  start_date: December 01, 2020
  time: ''
  title: Jetstream Training Session for ECSS Consultants
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2234/session/3895/register"
- categroy: Workshop
  end_date: December 02, 2020
  source: XSEDE
  start_date: December 01, 2020
  time: ''
  title: 'XSEDE HPC Workshop: Big Data and Machine Learning - December 1-2, 2020'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2236/session/3897/register"
- categroy: Workshop
  end_date: December 08, 2020
  source: XSEDE
  start_date: December 08, 2020
  time: ''
  title: AMD Training for ECSS Consultants
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2235/session/3896/register"
- categroy: Workshop
  end_date: December 11, 2020
  source: InCommon
  start_date: December 08, 2020
  time: ''
  title: midPoint Virtual Training
  website: "https://incommon.org/academy/midpoint-evolveum/"
- categroy: Workshop
  end_date: December 10, 2020
  source: XSEDE
  start_date: December 10, 2020
  time: ''
  title: 'XSEDE Webinar: Running Jupyter Notebooks on Expanse, Thursday, December
    10, 2020, 11am-noon PST'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2200/session/3861/register"
- categroy: Workshop
  end_date: February 02, 2021
  source: TACC
  start_date: February 02, 2021
  time: ''
  title: Introduction to Machine Learning at TACC
  website: "https://learn.tacc.utexas.edu/course/view.php?id=99"
- categroy: Workshop
  end_date: February 09, 2021
  source: TACC
  start_date: February 09, 2021
  time: ''
  title: Introduction to Deep Learning at TACC
  website: "https://learn.tacc.utexas.edu/course/view.php?id=100"
- categroy: Workshop
  end_date: February 10, 2021
  source: TACC
  start_date: February 10, 2021
  time: ''
  title: Introduction to Linux
  website: "https://learn.tacc.utexas.edu/course/view.php?id=101"
- categroy: Workshop
  end_date: February 18, 2021
  source: TACC
  start_date: February 18, 2021
  time: ''
  title: C++ for C Programmers
  website: "https://learn.tacc.utexas.edu/course/view.php?id=102"
- categroy: Workshop
  end_date: February 25, 2021
  source: TACC
  start_date: February 25, 2021
  time: ''
  title: MPL Object-Oriented Interface to MPI
  website: "https://learn.tacc.utexas.edu/course/view.php?id=103"