- categroy: Workshop
  end_date: August 12, 2022
  source: XSEDE
  start_date: August 12, 2022
  time: 04:00
  title: An Interactive Computing Overview on Anvil
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/3091/session/4884/register"