- categroy: Workshop
  end_date: December 11, 2020
  source: InCommon
  start_date: December 08, 2020
  time: ''
  title: midPoint Virtual Training
  website: "https://incommon.org/academy/midpoint-evolveum/"
- categroy: Workshop
  end_date: February 02, 2021
  source: TACC
  start_date: February 02, 2021
  time: ''
  title: Introduction to Machine Learning at TACC
  website: "https://learn.tacc.utexas.edu/course/view.php?id=99"
- categroy: Workshop
  end_date: February 09, 2021
  source: TACC
  start_date: February 09, 2021
  time: ''
  title: Introduction to Deep Learning at TACC
  website: "https://learn.tacc.utexas.edu/course/view.php?id=100"
- categroy: Workshop
  end_date: February 10, 2021
  source: TACC
  start_date: February 10, 2021
  time: ''
  title: Introduction to Linux
  website: "https://learn.tacc.utexas.edu/course/view.php?id=101"
- categroy: Workshop
  end_date: February 18, 2021
  source: TACC
  start_date: February 18, 2021
  time: ''
  title: C++ for C Programmers
  website: "https://learn.tacc.utexas.edu/course/view.php?id=102"
- categroy: Workshop
  end_date: February 25, 2021
  source: TACC
  start_date: February 25, 2021
  time: ''
  title: MPL Object-Oriented Interface to MPI
  website: "https://learn.tacc.utexas.edu/course/view.php?id=103"