- categroy: Workshop
  date: March 07, 2020
  title: CSULA Student Training Series 2020- XSEDE Intro to Linux/Unix (Cal State
    LA)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2013/session/3524/register"
- categroy: Workshop
  date: March 18, 2020
  title: Writing a Successful XSEDE Allocation Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/3632/register"
- categroy: Workshop
  date: March 19, 2020
  title: 'XSEDE Webinar: Using the Seedme Data Management System on Comet'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2035/session/3630/register"
- categroy: Workshop
  date: March 20, 2020
  title: XSEDE New User Training March 20, 2020
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2040/session/3635/register"
- categroy: Workshop
  date: March 21, 2020
  title: CSULA Student Training Series 2020- XSEDE Python 1 in Linux/Unix (Cal State
    LA)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2014/session/3525/register"
- categroy: Workshop
  date: March 28, 2020
  title: CSULA Student Training Series 2020- XSEDE Python 2 in Linux/Unix (Cal State
    LA)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2015/session/3526/register"
- categroy: Workshop
  date: April 02, 2020
  title: Introduction to Research Computing Using the Illinois Campus Cluster (Illini
    Hall, University of Illinois at Urbana-Champaign)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2039/session/3634/register"