- categroy: Workshop
  end_date: July 08, 2022
  source: XSEDE
  start_date: July 08, 2022
  time: 04:00
  title: Writing a Successful XSEDE Research Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/4719/register"