- categroy: Workshop
  end_date: November 03, 2021
  source: XSEDE
  start_date: November 03, 2021
  time: 04:00
  title: Using the NVIDIA software ecosystem on the NVIDIA Ampere A100 and A40 GPUs
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2568/session/4266/register"
- categroy: Workshop
  end_date: November 03, 2021
  source: XSEDE
  start_date: November 03, 2021
  time: 04:00
  title: 'XSEDE HPC Workshop: OpenMP - November 3, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2567/session/4265/register"
- categroy: Workshop
  end_date: November 10, 2021
  source: CyVerse
  start_date: November 07, 2021
  time: 04:00
  title: A Creative Economy for Sustainable Development
  website: "https://cyverse.org/acsmeeting2021"
- categroy: Workshop
  end_date: November 17, 2021
  source: XSEDE
  start_date: November 17, 2021
  time: 05:00
  title: Introduction to Parallel Computing
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2569/session/4267/register"