- categroy: Workshop
  date: 2020-03-09 00:00:00 - 2020-04-08 00:00:00
  source: XSEDE
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020 (Arizona State University)
  website: "Registration closed"
- categroy: Workshop
  date: '2020-03-20 00:00:00'
  source: XSEDE
  title: XSEDE New User Training March 20, 2020
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2040/session/3635/register"
- categroy: Workshop
  date: '2020-03-21 00:00:00'
  source: XSEDE
  title: CSULA Student Training Series 2020- XSEDE Python 1 in Linux/Unix (Cal State
    LA)
  website: "Registration closed"
- categroy: Workshop
  date: '2020-03-28 00:00:00'
  source: XSEDE
  title: CSULA Student Training Series 2020- XSEDE Python 2 in Linux/Unix (Cal State
    LA)
  website: "Registration closed"
- categroy: Workshop
  date: '2020-04-02 00:00:00'
  source: XSEDE
  title: Introduction to Research Computing Using the Illinois Campus Cluster (Illini
    Hall, University of Illinois at Urbana-Champaign)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2039/session/3634/register"
- categroy: Workshop
  date: 2020-04-07 00:00:00 - 2020-04-08 00:00:00
  source: XSEDE
  title: XSEDE HPC Workshop Big Data - April 7-8, 2020
  website: "Multiple"
- categroy: Workshop
  date: '2020-04-16 00:00:00'
  source: XSEDE
  title: 'XSEDE Webinar: Running Jupyter Notebooks on Comet'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2042/session/3661/register"
- categroy: Workshop
  date: 2020-06-01 00:00:00 - 2020-06-05 00:00:00
  source: XSEDE
  title: Computational Chemistry for Chemistry Educators Workshop (Mount Saint Mary
    College)
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2038/session/3633/register"
- categroy: Workshop
  date: March 20th, 2020 1pm-3pm CT
  source: TACC
  title: BOINC@TACC
  website: "https://learn.tacc.utexas.edu/course/view.php?id=85"
- categroy: Workshop
  date: March 23-27, 2020
  source: LCI
  title: LCI Intermediate Workshop
  website: "http://linuxclustersinstitute.org/workshops/interm20/register.php"
- categroy: Workshop
  date: May 19-21, 2020
  source: LCI
  title: LCI Advanced Workshop
  website: "http://linuxclustersinstitute.org/workshops/advanced20/register.php"