- categroy: Workshop
  end_date: July 31, 2020
  source: PEARC
  start_date: July 27, 2020
  time: 04:00
  title: PEARC20
  website: "https://pearc.acm.org/pearc20/registration/"
- categroy: Workshop
  end_date: August 05, 2020
  source: XSEDE
  start_date: August 04, 2020
  time: ''
  title: 'XSEDE HPC Workshop: Big Data and Machine Learning - August 4-5, 2020'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2067/session/3685/register"
- categroy: Workshop
  end_date: September 18, 2020
  source: TACC
  start_date: September 17, 2020
  time: ''
  title: TACCSTER 2020
  website: "https://learn.tacc.utexas.edu/course/view.php?id=92"
- categroy: Workshop
  end_date: October 22, 2020
  source: TACC
  start_date: October 22, 2020
  time: ''
  title: High Performance Computing on Frontera Day 1
  website: "https://learn.tacc.utexas.edu/course/view.php?id=94"
- categroy: Workshop
  end_date: October 29, 2020
  source: TACC
  start_date: October 29, 2020
  time: ''
  title: High Performance Computing on Frontera Day 2
  website: "https://learn.tacc.utexas.edu/course/view.php?id=95"