- categroy: Workshop
  end_date: October 13, 2021
  source: XSEDE
  start_date: October 06, 2021
  time: 04:00
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Agent-based Modeling'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2366/session/4257/register"
- categroy: Workshop
  end_date: October 13, 2021
  source: XSEDE
  start_date: October 06, 2021
  time: 04:00
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    3) Agent-based Modeling'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2366/session/4257/register"
- categroy: Workshop
  end_date: October 12, 2021
  source: XSEDE
  start_date: October 12, 2021
  time: 04:00
  title: Writing a Successful XSEDE Allocation Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/4264/register"
- categroy: Workshop
  end_date: October 21, 2021
  source: XSEDE
  start_date: October 21, 2021
  time: 04:00
  title: 'XSEDE Webinar: Data Management & File Systems on Expanse'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2531/session/4225/register"
- categroy: Workshop
  end_date: October 22, 2021
  source: CyVerse
  start_date: October 22, 2021
  time: 04:00
  title: 'Webinar: All About Apps in CyVerse'
  website: "https://cyverse.org/apps-webinar"
- categroy: Workshop
  end_date: November 03, 2021
  source: XSEDE
  start_date: November 03, 2021
  time: 04:00
  title: 'XSEDE HPC Workshop: OpenMP - November 3, 2021'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2567/session/4265/register"
- categroy: Workshop
  end_date: November 10, 2021
  source: CyVerse
  start_date: November 07, 2021
  time: 04:00
  title: A Creative Economy for Sustainable Development
  website: "https://cyverse.org/acsmeeting2021"