- categroy: Workshop
  end_date: June 15, 2021
  source: XSEDE
  start_date: June 07, 2021
  time: ''
  title: Computational Chemistry for Chemistry Educators Workshop
  website: "Registration opens"
- categroy: Workshop
  end_date: June 16, 2021
  source: XSEDE
  start_date: June 15, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    1) Modeling with Spreadsheets and Web Resources'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2339/session/4003/register"
- categroy: Workshop
  end_date: June 16, 2021
  source: XSEDE
  start_date: June 15, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Using
    Spreadsheets'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 16, 2021
  source: XSEDE
  start_date: June 15, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Modeling with Spreadsheets'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 16, 2021
  source: XSEDE
  start_date: June 15, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Modeling with Spreadsheets and Web Resources'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2339/session/4003/register"
- categroy: Workshop
  end_date: June 18, 2021
  source: XSEDE
  start_date: June 17, 2021
  time: ''
  title: 'Workshop: Advanced Computing for Social Change Curriculum Development'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2335/session/3998/register"
- categroy: Workshop
  end_date: June 17, 2021
  source: XSEDE
  start_date: June 17, 2021
  time: ''
  title: 'XSEDE Webinar: Overview of Visualization on Expanse, Thursday, June 17,
    2021, 11am-Noon PT'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2367/session/4028/register"
- categroy: Workshop
  end_date: June 17, 2021
  source: XSEDE
  start_date: June 17, 2021
  time: ''
  title: XSEDE New User Training
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2432/session/4093/register"
- categroy: Workshop
  end_date: June 23, 2021
  source: XSEDE
  start_date: June 22, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Systems
    Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 23, 2021
  source: XSEDE
  start_date: June 22, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Systems Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 23, 2021
  source: XSEDE
  start_date: June 22, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Using
    Systems Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 23, 2021
  source: XSEDE
  start_date: June 22, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    2) Systems Modeling'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2365/session/4026/register"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    3) Agent-based Modeling'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2366/session/4027/register"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Using
    Agent Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Agent-based Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum:
    Agent Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: June 30, 2021
  source: XSEDE
  start_date: June 29, 2021
  time: ''
  title: 'Workshop: Introduction to Computational Thinking Across the Curriculum Agent
    Modeling'
  website: "Registration opens"
- categroy: Workshop
  end_date: July 13, 2021
  source: XSEDE
  start_date: July 12, 2021
  time: ''
  title: Advanced Computing for Social Change (ACSC) Curriculum Development Workshop
    for AUCC
  website: "Registration opens"
- categroy: Workshop
  end_date: July 30, 2021
  source: XSEDE
  start_date: July 18, 2021
  time: ''
  title: IHPCSS 2021 Hands-on Training
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2431/session/4092/register"