- categroy: Workshop
  end_date: July 31, 2020
  source: CyVerse
  start_date: July 27, 2020
  time: ''
  title: Plant Biology 2020
  website: "https://cyverse.org/plant-biology-2020"
- categroy: Workshop
  end_date: August 05, 2020
  source: XSEDE
  start_date: August 04, 2020
  time: ''
  title: 'XSEDE HPC Workshop: Big Data and Machine Learning - August 4-5, 2020'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2067/session/3685/register"