- categroy: Workshop
  end_date: June 24, 2020
  source: XSEDE
  start_date: June 24, 2020
  time: ''
  title: XSEDE Code Performance and Scaling Training
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2064/session/3681/register"
- categroy: Workshop
  end_date: July 01, 2020
  source: XSEDE
  start_date: July 01, 2020
  time: ''
  title: Writing a Successful XSEDE Allocation Proposal
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/594/session/3682/register"
- categroy: Workshop
  end_date: July 16, 2020
  source: XSEDE
  start_date: July 16, 2020
  time: ''
  title: 'XSEDE Webinar: Indispensable Security: Tips to Use SDSC''s HPC Resources
    Securely'
  website: "https://www.xsede.org/web/xup/course-calendar/-/training-user/class/2063/session/3680/register"
- categroy: Workshop
  end_date: July 21, 2020
  source: CyVerse
  start_date: July 19, 2020
  time: ''
  title: Bioinformatics Community Conference
  website: "https://cyverse.org/bcc2020"
- categroy: Workshop
  end_date: July 24, 2020
  source: XSEDE
  start_date: July 20, 2020
  time: ''
  title: ACSC Faculty Curriculum Development Workshop
  website: "Registration opens"
- categroy: Workshop
  end_date: July 24, 2020
  source: XSEDE
  start_date: July 20, 2020
  time: ''
  title: ACSC Faculty New User Training
  website: "Registration opens"
- categroy: Workshop
  end_date: July 31, 2020
  source: CyVerse
  start_date: July 27, 2020
  time: ''
  title: Plant Biology 2020
  website: "https://cyverse.org/plant-biology-2020"